services:
  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: boise_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - scribe_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: boise_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/models:/app/models
      - ./Backend/logs:/app/logs
      - ./Backend:/app  # Add this to sync all files
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - WHISPER_MODEL=tiny  # Use tiny model for faster loading
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}  # Pass HF token for speaker diarization
    env_file:
      - .env  # Load all environment variables from .env file
    networks:
      - scribe_network
    restart: unless-stopped
    depends_on:
      - ollama
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  # Frontend React App
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: boise_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WS_URL=ws://localhost:8000/ws/audio
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - scribe_network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  scribe_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local